# Generated by Django 3.2.4 on 2023-05-22 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FatClassification',
            fields=[
                ('model_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('gender', models.IntegerField()),
                ('age', models.FloatField()),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('family_history_with_overweight', models.IntegerField()),
                ('FAVC', models.IntegerField()),
                ('FCVC', models.FloatField()),
                ('NCP', models.FloatField()),
                ('CAEC', models.CharField(choices=[('no', 'нет'), ('Sometimes', 'иногда'), ('Frequently', 'часто'), ('Always', 'всегда')], default='no', max_length=255)),
                ('SMOKE', models.IntegerField()),
                ('CH2O', models.FloatField()),
                ('SCC', models.IntegerField()),
                ('FAF', models.FloatField()),
                ('TUE', models.FloatField()),
                ('CALC', models.CharField(choices=[('no', 'нет'), ('Sometimes', 'иногда'), ('Frequently', 'часто'), ('Always', 'всегда')], default='no', max_length=255)),
                ('MTRANS', models.CharField(choices=[('Automobile', 'на машине'), ('Motorbike', 'на мотоцикле'), ('Bike', 'на велосипеде'), ('Public Transportation', 'на общественном транспорте'), ('Walking', 'пешком')], default='Walking', max_length=255)),
                ('nobeyesdad', models.CharField(blank=True, choices=[('Insufficient', 'недостаточный вес'), ('Normal', 'нормальный вес'), ('Overweight_I', 'избыточный вес 1-й стадии'), ('Overweight_II', 'избыточный вес 2-й стадии'), ('Obesity_I', 'ожирение 1-й стадии'), ('Obesity_II', 'ожирение 2-й стадии'), ('Obesity_III', 'ожирение 3-й стадии')], default='', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Данные о человеке для классификации',
            },
        ),
    ]
