# Generated by Django 4.2.5 on 2023-09-10 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0003_auto_20230522_2255'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextTranslationResult',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('input_text', models.CharField(blank=True, max_length=255)),
                ('output_text', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='FatClassification',
        ),
    ]
