# Generated by Django 4.2.5 on 2023-09-10 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0004_texttranslationresult_delete_fatclassification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texttranslationresult',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
