# Generated by Django 4.2.5 on 2023-09-10 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0005_alter_texttranslationresult_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texttranslationresult',
            name='input_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='texttranslationresult',
            name='output_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
